default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: postgres
  database: db

development:
  <<: *default
  database: db

test:
  <<: *default
  database: blog_test_db

production:
  <<: *default
  database: db

